-- MySQL Script generated by MySQL Workbench
-- Wed Feb 28 19:00:40 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NULL,
  `nombre` VARCHAR(225) NULL,
  `idrol` INT NULL,
  `contra` VARCHAR(45) NULL,
  `usuariocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idusuario_UNIQUE` (`idusuario` ASC),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria` (
  `idcategoria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `prioridad` INT NULL DEFAULT 1,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporte` (
  `idreporte` INT NOT NULL AUTO_INCREMENT,
  `fechaini` DATE NULL,
  `fechamod` DATE NULL,
  `idestado` INT NULL,
  `idcategoria` INT NULL,
  `idoperador` INT NULL,
  `prioridad` INT NOT NULL DEFAULT 0,
  `idempresa` INT NULL,
  PRIMARY KEY (`idreporte`),
  UNIQUE INDEX `idreporte_UNIQUE` (`idreporte` ASC),
  INDEX `idoperador_idx` (`idoperador` ASC),
  INDEX `idcategoria_idx` (`idcategoria` ASC),
  CONSTRAINT `idoperador`
    FOREIGN KEY (`idoperador`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `idcategoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `categoria` (`idcategoria`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensaje` (
  `idmensaje` INT NOT NULL,
  `idreporte` INT NULL,
  `fecha` DATE NULL,
  `cuerpo` TEXT NULL,
  `tipo` INT NULL,
  PRIMARY KEY (`idmensaje`),
  UNIQUE INDEX `idmensaje_UNIQUE` (`idmensaje` ASC),
  INDEX `idreporte_idx` (`idreporte` ASC),
  CONSTRAINT `idreporte`
    FOREIGN KEY (`idreporte`)
    REFERENCES `reporte` (`idreporte`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `msjusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msjusuario` (
  `idmensaje` INT NOT NULL,
  `idusuario` INT NULL,
  PRIMARY KEY (`idmensaje`),
  UNIQUE INDEX `idmensaje_UNIQUE` (`idmensaje` ASC),
  CONSTRAINT `idmensajes`
    FOREIGN KEY (`idmensaje`)
    REFERENCES `mensaje` (`idmensaje`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `msjcliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `msjcliente` (
  `idmensaje` INT NOT NULL,
  `correocliente` VARCHAR(45) NULL,
  PRIMARY KEY (`idmensaje`),
  UNIQUE INDEX `idmensaje_UNIQUE` (`idmensaje` ASC),
  CONSTRAINT `idmensaje`
    FOREIGN KEY (`idmensaje`)
    REFERENCES `mensaje` (`idmensaje`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `archivo` (
  `idarchivo` INT NOT NULL,
  `ruta` VARCHAR(45) NULL,
  `tipo` INT NULL,
  `idmensaje` INT NULL,
  PRIMARY KEY (`idarchivo`),
  UNIQUE INDEX `idarchivo_UNIQUE` (`idarchivo` ASC),
  INDEX `idmensaje_idx` (`idmensaje` ASC),
  CONSTRAINT `idmensaje`
    FOREIGN KEY (`idmensaje`)
    REFERENCES `mensaje` (`idmensaje`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `empresa` (
  `idempresa` INT NULL,
  `empresacol` VARCHAR(45) NULL,
  PRIMARY KEY (`idempresa`),
  UNIQUE INDEX `idempresa_UNIQUE` (`idempresa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporte_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporte_empresa` (
  `idreporte` INT NOT NULL,
  `idempresa` INT NOT NULL,
  PRIMARY KEY (`idreporte`),
  INDEX `idempresa_idx` (`idempresa` ASC),
  INDEX `fk_reporte_empresa_reporte1_idx` (`idreporte` ASC),
  CONSTRAINT `idempresa`
    FOREIGN KEY (`idempresa`)
    REFERENCES `empresa` (`idempresa`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_reporte_empresa_reporte1`
    FOREIGN KEY (`idreporte`)
    REFERENCES `reporte` (`idreporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporte_local`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporte_local` (
  `idreporte` INT NOT NULL,
  `correocliente` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono1` VARCHAR(10) NULL,
  `telefono2` VARCHAR(10) NULL,
  `telefono3` VARCHAR(10) NULL,
  `propiedades` TEXT NULL,
  PRIMARY KEY (`idreporte`),
  CONSTRAINT `fk_reporte_local_reporte1`
    FOREIGN KEY (`idreporte`)
    REFERENCES `reporte` (`idreporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mensaje_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mensaje_usuarios` (
  `idusuario_emisor` INT NOT NULL,
  `idusuario_receptor` INT NULL,
  `mensaje` TEXT NULL,
  `fecha` DATETIME NULL,
  INDEX `idemisor_idx` (`idusuario_emisor` ASC),
  INDEX `idreceptor_idx` (`idusuario_receptor` ASC),
  CONSTRAINT `idemisor`
    FOREIGN KEY (`idusuario_emisor`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idreceptor`
    FOREIGN KEY (`idusuario_receptor`)
    REFERENCES `usuario` (`idusuario`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
